class CreateScripts < ActiveRecord::Migration
  def change
    create_table :scripts do |t|
      t.string :name
      t.string :play1
      t.string :play2
      t.string :play3
      t.string :play4
      t.string :play5
      t.string :play6
      t.string :play7
      t.string :play8
      t.string :play9
      t.string :play10
      t.string :play11
      t.string :play12
      t.string :play13
      t.string :play14
      t.string :play15
      t.string :play16
      t.string :play17
      t.string :play18
      t.string :play19
      t.string :play20
      t.string :play21
      t.string :play22
      t.string :play23
      t.string :play24
      t.string :play25
      t.string :play26
      t.string :play27
      t.string :play28
      t.string :play29
      t.string :play30
      t.string :play31
      t.string :play32
      t.string :play33
      t.string :play34
      t.string :play35
      t.string :play36
      t.string :play37
      t.string :play38
      t.string :play39
      t.string :play40
      t.string :play41
      t.string :play42
      t.string :play43
      t.string :play44
      t.string :play45
      t.string :play46
      t.string :play47
      t.string :play48
      t.string :play49
      t.string :play50
      t.string :play51
      t.string :play52
      t.string :play53
      t.string :play54
      t.string :play55
      t.string :play56
      t.string :play57
      t.string :play58
      t.string :play59
      t.string :play60
      t.string :play61
      t.string :play62
      t.string :play63
      t.string :play64
      t.string :play65
      t.string :play66
      t.string :play67
      t.string :play68
      t.string :play69
      t.string :play70
      t.string :play71
      t.string :play72
      t.string :play73
      t.string :play74
      t.string :play75
      t.string :play76
      t.string :play77
      t.string :play78
      t.string :play79
      t.string :play80
      t.string :play81
      t.string :play82
      t.string :play83
      t.string :play84
      t.string :play85
      t.string :play86
      t.string :play87
      t.string :play88
      t.string :play89
      t.string :play90
      t.string :play91
      t.string :play92
      t.string :play93
      t.string :play94
      t.string :play95
      t.string :play96
      t.string :play97
      t.string :play98
      t.string :play99
      t.string :play100
      t.string :hash1
      t.string :hash2
      t.string :hash3
      t.string :hash4
      t.string :hash5
      t.string :hash6
      t.string :hash7
      t.string :hash8
      t.string :hash9
      t.string :hash10
      t.string :hash11
      t.string :hash12
      t.string :hash13
      t.string :hash14
      t.string :hash15
      t.string :hash16
      t.string :hash17
      t.string :hash18
      t.string :hash19
      t.string :hash20
      t.string :hash21
      t.string :hash22
      t.string :hash23
      t.string :hash24
      t.string :hash25
      t.string :hash26
      t.string :hash27
      t.string :hash28
      t.string :hash29
      t.string :hash30
      t.string :hash31
      t.string :hash32
      t.string :hash33
      t.string :hash34
      t.string :hash35
      t.string :hash36
      t.string :hash37
      t.string :hash38
      t.string :hash39
      t.string :hash40
      t.string :hash41
      t.string :hash42
      t.string :hash43
      t.string :hash44
      t.string :hash45
      t.string :hash46
      t.string :hash47
      t.string :hash48
      t.string :hash49
      t.string :hash50
      t.string :hash51
      t.string :hash52
      t.string :hash53
      t.string :hash54
      t.string :hash55
      t.string :hash56
      t.string :hash57
      t.string :hash58
      t.string :hash59
      t.string :hash60
      t.string :hash61
      t.string :hash62
      t.string :hash63
      t.string :hash64
      t.string :hash65
      t.string :hash66
      t.string :hash67
      t.string :hash68
      t.string :hash69
      t.string :hash70
      t.string :hash71
      t.string :hash72
      t.string :hash73
      t.string :hash74
      t.string :hash75
      t.string :hash76
      t.string :hash77
      t.string :hash78
      t.string :hash79
      t.string :hash80
      t.string :hash81
      t.string :hash82
      t.string :hash83
      t.string :hash84
      t.string :hash85
      t.string :hash86
      t.string :hash87
      t.string :hash88
      t.string :hash89
      t.string :hash90
      t.string :hash91
      t.string :hash92
      t.string :hash93
      t.string :hash94
      t.string :hash95
      t.string :hash96
      t.string :hash97
      t.string :hash98
      t.string :hash99
      t.string :hash100
      t.string :down1
      t.string :down2
      t.string :down3
      t.string :down4
      t.string :down5
      t.string :down6
      t.string :down7
      t.string :down8
      t.string :down9
      t.string :down10
      t.string :down11
      t.string :down12
      t.string :down13
      t.string :down14
      t.string :down15
      t.string :down16
      t.string :down17
      t.string :down18
      t.string :down19
      t.string :down20
      t.string :down21
      t.string :down22
      t.string :down23
      t.string :down24
      t.string :down25
      t.string :down26
      t.string :down27
      t.string :down28
      t.string :down29
      t.string :down30
      t.string :down31
      t.string :down32
      t.string :down33
      t.string :down34
      t.string :down35
      t.string :down36
      t.string :down37
      t.string :down38
      t.string :down39
      t.string :down40
      t.string :down41
      t.string :down42
      t.string :down43
      t.string :down44
      t.string :down45
      t.string :down46
      t.string :down47
      t.string :down48
      t.string :down49
      t.string :down50
      t.string :down51
      t.string :down52
      t.string :down53
      t.string :down54
      t.string :down55
      t.string :down56
      t.string :down57
      t.string :down58
      t.string :down59
      t.string :down60
      t.string :down61
      t.string :down62
      t.string :down63
      t.string :down64
      t.string :down65
      t.string :down66
      t.string :down67
      t.string :down68
      t.string :down69
      t.string :down70
      t.string :down71
      t.string :down72
      t.string :down73
      t.string :down74
      t.string :down75
      t.string :down76
      t.string :down77
      t.string :down78
      t.string :down79
      t.string :down80
      t.string :down81
      t.string :down82
      t.string :down83
      t.string :down84
      t.string :down85
      t.string :down86
      t.string :down87
      t.string :down88
      t.string :down89
      t.string :down90
      t.string :down91
      t.string :down92
      t.string :down93
      t.string :down94
      t.string :down95
      t.string :down96
      t.string :down97
      t.string :down98
      t.string :down99
      t.string :down100
      t.string :distance1
      t.string :distance2
      t.string :distance3
      t.string :distance4
      t.string :distance5
      t.string :distance6
      t.string :distance7
      t.string :distance8
      t.string :distance9
      t.string :distance10
      t.string :distance11
      t.string :distance12
      t.string :distance13
      t.string :distance14
      t.string :distance15
      t.string :distance16
      t.string :distance17
      t.string :distance18
      t.string :distance19
      t.string :distance20
      t.string :distance21
      t.string :distance22
      t.string :distance23
      t.string :distance24
      t.string :distance25
      t.string :distance26
      t.string :distance27
      t.string :distance28
      t.string :distance29
      t.string :distance30
      t.string :distance31
      t.string :distance32
      t.string :distance33
      t.string :distance34
      t.string :distance35
      t.string :distance36
      t.string :distance37
      t.string :distance38
      t.string :distance39
      t.string :distance40
      t.string :distance41
      t.string :distance42
      t.string :distance43
      t.string :distance44
      t.string :distance45
      t.string :distance46
      t.string :distance47
      t.string :distance48
      t.string :distance49
      t.string :distance50
      t.string :distance51
      t.string :distance52
      t.string :distance53
      t.string :distance54
      t.string :distance55
      t.string :distance56
      t.string :distance57
      t.string :distance58
      t.string :distance59
      t.string :distance60
      t.string :distance61
      t.string :distance62
      t.string :distance63
      t.string :distance64
      t.string :distance65
      t.string :distance66
      t.string :distance67
      t.string :distance68
      t.string :distance69
      t.string :distance70
      t.string :distance71
      t.string :distance72
      t.string :distance73
      t.string :distance74
      t.string :distance75
      t.string :distance76
      t.string :distance77
      t.string :distance78
      t.string :distance79
      t.string :distance80
      t.string :distance81
      t.string :distance82
      t.string :distance83
      t.string :distance84
      t.string :distance85
      t.string :distance86
      t.string :distance87
      t.string :distance88
      t.string :distance89
      t.string :distance90
      t.string :distance91
      t.string :distance92
      t.string :distance93
      t.string :distance94
      t.string :distance95
      t.string :distance96
      t.string :distance97
      t.string :distance98
      t.string :distance99
      t.string :distance100
      t.string :defense1
      t.string :defense2
      t.string :defense3
      t.string :defense4
      t.string :defense5
      t.string :defense6
      t.string :defense7
      t.string :defense8
      t.string :defense9
      t.string :defense10
      t.string :defense11
      t.string :defense12
      t.string :defense13
      t.string :defense14
      t.string :defense15
      t.string :defense16
      t.string :defense17
      t.string :defense18
      t.string :defense19
      t.string :defense20
      t.string :defense21
      t.string :defense22
      t.string :defense23
      t.string :defense24
      t.string :defense25
      t.string :defense26
      t.string :defense27
      t.string :defense28
      t.string :defense29
      t.string :defense30
      t.string :defense31
      t.string :defense32
      t.string :defense33
      t.string :defense34
      t.string :defense35
      t.string :defense36
      t.string :defense37
      t.string :defense38
      t.string :defense39
      t.string :defense40
      t.string :defense41
      t.string :defense42
      t.string :defense43
      t.string :defense44
      t.string :defense45
      t.string :defense46
      t.string :defense47
      t.string :defense48
      t.string :defense49
      t.string :defense50
      t.string :defense51
      t.string :defense52
      t.string :defense53
      t.string :defense54
      t.string :defense55
      t.string :defense56
      t.string :defense57
      t.string :defense58
      t.string :defense59
      t.string :defense60
      t.string :defense61
      t.string :defense62
      t.string :defense63
      t.string :defense64
      t.string :defense65
      t.string :defense66
      t.string :defense67
      t.string :defense68
      t.string :defense69
      t.string :defense70
      t.string :defense71
      t.string :defense72
      t.string :defense73
      t.string :defense74
      t.string :defense75
      t.string :defense76
      t.string :defense77
      t.string :defense78
      t.string :defense79
      t.string :defense80
      t.string :defense81
      t.string :defense82
      t.string :defense83
      t.string :defense84
      t.string :defense85
      t.string :defense86
      t.string :defense87
      t.string :defense88
      t.string :defense89
      t.string :defense90
      t.string :defense91
      t.string :defense92
      t.string :defense93
      t.string :defense94
      t.string :defense95
      t.string :defense96
      t.string :defense97
      t.string :defense98
      t.string :defense99
      t.string :defense100
      t.string :situation1
      t.string :situation2
      t.string :situation3
      t.string :situation4
      t.integer :sed_id

      t.timestamps
    end
  end
end
